server:
  port: 8080
zuul:
#  ignoredServices: *
  prefix: /api
  stripPrefix: false
  routes:
    pod8:
      path: /v1/**
      serviceId: pod8
      stripPrefix: false

    pod9:
      path: /v1/**
      serviceId: pod9
      stripPrefix: false

    podany:
      path: /v1/**
      serviceId: podany
      stripPrefix: false

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 0 #don't want to retry on the same server
  MaxAutoRetriesNextServer: 2
  okhttp:
    enabled: true
  OkToRetryOnAllOperations: true
  eureka:
    enabled: true

pod8:
  ribbon:
    retryable: true
    listOfServers: http://api_app_08_00,http://api_app_08_01,http://api_app_08_02

pod9:
  ribbon:
    retryable: true
    listOfServers: http://api_app_09_00,http://api_app_09_01,http://api_app_09_02

podany:
  ribbon:
    retryable: true
    listOfServers: http://api_app_08_00,http://api_app_08_01,http://api_app_08_02,http://api_app_09_00,http://api_app_09_01,http://api_app_09_02



hystrix:
  command:
    pod8:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000
    pod9:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000
    podany:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000